apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: comfyui
  name: confyui-pvc
  namespace: open-webui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi